# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spurctx < Formula
  desc ""
  homepage "https://github.com/spurintel/spurctx-cli"
  version "1.0.5"

  on_macos do
    url "https://github.com/spurintel/spurctx-cli/releases/download/1.0.5/spurctx-cli_1.0.5_darwin_all.tar.gz"
    sha256 "215abba151e77251ff4d62bbf4d9558a794eeefa10e0a6a037c78a40b4e9e633"

    def install
      bin.install "spurctx-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/spurintel/spurctx-cli/releases/download/1.0.5/spurctx-cli_1.0.5_linux_amd64.tar.gz"
      sha256 "e1a269b13a1468a8c5d99c6196c53b3bb55fc10bcd76744e11b95d905befc3f2"

      def install
        bin.install "spurctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spurintel/spurctx-cli/releases/download/1.0.5/spurctx-cli_1.0.5_linux_arm64.tar.gz"
      sha256 "fd51556a89da8bee04cbffe1c9a73d867c24dda6efcc6df763bc93df147f1c7c"

      def install
        bin.install "spurctx"
      end
    end
  end
end
