# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spurctx < Formula
  desc ""
  homepage "https://github.com/spurintel/spurctx-cli"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/spurintel/spurctx-cli/releases/download/v0.0.5/spurctx-cli_0.0.5_darwin_arm64.tar.gz"
      sha256 "cbc2633614573fd5f0843da28bafef2a00e3ad6339b4addba6f5370193982865"

      def install
        bin.install "spurctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/spurintel/spurctx-cli/releases/download/v0.0.5/spurctx-cli_0.0.5_darwin_amd64.tar.gz"
      sha256 "724be180b775315532e4edad74523290c066fa51870a4050c5c34cdd731934a4"

      def install
        bin.install "spurctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spurintel/spurctx-cli/releases/download/v0.0.5/spurctx-cli_0.0.5_linux_arm64.tar.gz"
      sha256 "740f18f3d0d53a12c7488bdaf6667533ef2a292c60a0893ed97219446ec00852"

      def install
        bin.install "spurctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/spurintel/spurctx-cli/releases/download/v0.0.5/spurctx-cli_0.0.5_linux_amd64.tar.gz"
      sha256 "c0528d917a34646769a2bec8ca7fd9355910edc119db603d83f81df741c911f7"

      def install
        bin.install "spurctx"
      end
    end
  end
end
